### ISSUE TITLE
Pretrained net not working

### ISSUE THREAD

**Issue by ilChelo** [tbennun/cudnn-training#21]
Hi tbennun, 
first of all thank you for Lenet sample, great tutorial for beginners like me.
As you wrote .FromFile function, I wrote a .ToFile one for reuse of trained nets (just fwrite instead of fread!). If the pair to/from is working correctly ( I know that by simply comparing values), why am I not able to reach the same score of a freshly trained net? I mean... if I run your sample without modifications, the test after the training gives for example 2% of error. But if I save the weights after the training and I reload them (the very same weights) for the test then I get 90%... I'm sure I miss something... There are many parameters in ForwardPropagation function, do I have to save/restore them too? Missing some initializations?

Thank you in advance,
M.

**Comment by tbennun** [comment]
It can happen as a result of many problems. Can you post your code as a pull request so that I can inspect the diff?

**Comment by ilChelo** [comment]
Hi @tbennun , thank you very much for your reply!
Ehm... kind of new here at Github... pull requests are still in my "to do" list... 
Do you mind if I paste here? Changes are very few... (lines numbers refer to lenet.cu original file)

1. I put these lines at the end of the training loop after the line 957 _printf("Iteration time: %f ms\n", std::chrono::_[...]

**printf("Save data to file\n");
conv1.ToFile("conv1");
conv2.ToFile("conv2");
fc1.ToFile("fc1");
fc2.ToFile("fc2");**

2. the .ToFile function is a copy of .FromFile (for both conv and fc layers) with fwrite and "wb" instead of "fread" and "rb".

3. Called .FromFile lines (lines 789-792) after line 969 _TrainingContext test_context(FLAGS_gpu [...]_ in the tests' part of code

Best,
M.

**Comment by ilChelo** [comment]
Ops...not closing...sorry...keep open!
Just a note: I changed file names in "fc1" and "fc2" for fc layers.

**Comment by tbennun** [comment]
Notice that the memory of the trained parameters is never copied from the GPU to the CPU (it is copied the other way around in lines 896-903). Because of that, writing the CPU weights to a file will have the same result as not training at all. Please copy the weights back to the CPU first.

To create a pull request, you will need to fork your own version of the cudnn-training sample, clone it to your machine, modify it, and commit/push the changes. After that, surfing to the project website on Github will already suggest that you create a pull request (large green button).

It would be nice to have a "save weights to a file" flag. Feel free to create that pull request when it's working.

**Comment by ilChelo** [comment]
Did it... hope that the fork/commit/pull stuff has been done correctly.
Thanks.
M.

**Comment by tbennun** [comment]
By the way, is it working after my suggestion? If so, we can go ahead and close this issue.

**Comment by ilChelo** [comment]
Well...I'd say yes.
Thank you.
